/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApartmentRouteImport } from './routes/apartment'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NearbyCategoryIndexRouteImport } from './routes/nearby.$category.index'
import { Route as NearbyCategoryIdRouteImport } from './routes/nearby.$category.$id'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentRoute = ApartmentRouteImport.update({
  id: '/apartment',
  path: '/apartment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyCategoryIndexRoute = NearbyCategoryIndexRouteImport.update({
  id: '/nearby/$category/',
  path: '/nearby/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyCategoryIdRoute = NearbyCategoryIdRouteImport.update({
  id: '/nearby/$category/$id',
  path: '/nearby/$category/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apartment': typeof ApartmentRoute
  '/contact': typeof ContactRoute
  '/nearby/$category/$id': typeof NearbyCategoryIdRoute
  '/nearby/$category/': typeof NearbyCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apartment': typeof ApartmentRoute
  '/contact': typeof ContactRoute
  '/nearby/$category/$id': typeof NearbyCategoryIdRoute
  '/nearby/$category': typeof NearbyCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apartment': typeof ApartmentRoute
  '/contact': typeof ContactRoute
  '/nearby/$category/$id': typeof NearbyCategoryIdRoute
  '/nearby/$category/': typeof NearbyCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apartment'
    | '/contact'
    | '/nearby/$category/$id'
    | '/nearby/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apartment'
    | '/contact'
    | '/nearby/$category/$id'
    | '/nearby/$category'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apartment'
    | '/contact'
    | '/nearby/$category/$id'
    | '/nearby/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApartmentRoute: typeof ApartmentRoute
  ContactRoute: typeof ContactRoute
  NearbyCategoryIdRoute: typeof NearbyCategoryIdRoute
  NearbyCategoryIndexRoute: typeof NearbyCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartment': {
      id: '/apartment'
      path: '/apartment'
      fullPath: '/apartment'
      preLoaderRoute: typeof ApartmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby/$category/': {
      id: '/nearby/$category/'
      path: '/nearby/$category'
      fullPath: '/nearby/$category/'
      preLoaderRoute: typeof NearbyCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby/$category/$id': {
      id: '/nearby/$category/$id'
      path: '/nearby/$category/$id'
      fullPath: '/nearby/$category/$id'
      preLoaderRoute: typeof NearbyCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApartmentRoute: ApartmentRoute,
  ContactRoute: ContactRoute,
  NearbyCategoryIdRoute: NearbyCategoryIdRoute,
  NearbyCategoryIndexRoute: NearbyCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
